- name: "Creating roboshop user"
  ansible.builtin.user:
    name: roboshop
    state: present

- name: "Removing app directory if it exists"
  ansible.builtin.file:
    path: /app
    state: absent

- name: "Creating app directory"
  ansible.builtin.file:
    path: /app
    state: directory

- name: "Downloading {{ component }} code"
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{ component }}.zip"
    dest: /tmp/{{ component }}.zip

- name: "Extracting {{ component }} code"
  ansible.builtin.unarchive:
    src: /tmp/{{ component }}.zip
    dest: /app
    remote_src: yes
