- name: install mysql client
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: check cities schema exists or not
  ansible.builtin.command: mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
  register: schema

- name: print output
  ansible.builtin.debug:
    msg: "schema output: {{schema}}"

- name: Copy shipping.sql to the target server
  ansible.builtin.copy:
    src: shipping.sql    # Path to the shipping.sql file on the Ansible control machine
    dest: /app/schema/shipping.sql   # Target path on the remote server
    mode: '0644'   # Set the permissions for the copied file


# - name: load cities data
#   ansible.builtin.shell: "mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}}  < /app/schema/shipping.sql"
#   when: schema.stdout != "1"