- name: Disable old nodejs and enable nodejs 18
  ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
  when: component == "user"

- name: Install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present
  when: component == "user"

- name: "Copy package.json for user component"
  ansible.builtin.copy:
    src: userpackage.json # Ensure this file is in your Ansible context (same directory as playbook or specify full path)
    dest: /app/package.json
    owner: ec2-user
    group: ec2-user
    mode: "0644"
  when: component == "user"

- name: "Copy package.json for catalogue component"
  ansible.builtin.copy:
    src: package.json
    dest: /app/package.json
    owner: ec2-user
    group: ec2-user
    mode: "0644"
  when: component == 'catalogue'

- name: Install dependencies
  ansible.builtin.command: npm install
  args:
    chdir: /app
