- name: "Copy Jpa config"
  ansible.builtin.copy:
    src: JpaConfig.java
    dest: /app/src/main/java/com/instana/robotshop/shipping/JpaConfig.java
    owner: ec2-user
    group: ec2-user
    mode: "0644"

- name: "Copy app properties"
  ansible.builtin.copy:
    src: application.properties
    dest: /app/src/main/resources/application.properties
    owner: ec2-user
    group: ec2-user
    mode: "0644"
